### ISSUE TITLE
undefined method error occurs in ACMatcher

### ISSUE THREAD

**Issue by tkrs** [yanana/fluent-plugin-filter-list#98]
```
[warn]: #2 fluent/log.rb:351:warn: dump an error event: error_class=NoMethodError error="undefined method `failure' for nil:NilClass" location="/usr/local/bundle/gems/fluent-plugin-filter-list-0.7.3/lib/matcher.rb:16:in `block in matches?'"
```

**Comment by tkrs** [comment]
minimal case:

```rb
irb(main):001:0> require 'matcher'; Matchers::ACMatcher.new(%w[xy axyz]).matches? 'axee'
Traceback (most recent call last):
       16: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
       15: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
       14: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
       13: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       12: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       11: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
       10: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
        9: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
        8: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
        7: from /home/tkrs/.rbenv/versions/2.7.2/bin/irb:23:in `<top (required)>'
        6: from /home/tkrs/.rbenv/versions/2.7.2/bin/irb:23:in `load'
        5: from /home/tkrs/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):1
        3: from /home/tkrs/code/github.com/tkrs/fluent-plugin-filter-list/lib/matcher.rb:15:in `matches?'
        2: from /home/tkrs/code/github.com/tkrs/fluent-plugin-filter-list/lib/matcher.rb:15:in `each'
        1: from /home/tkrs/code/github.com/tkrs/fluent-plugin-filter-list/lib/matcher.rb:16:in `block in matches?'
NoMethodError (undefined method `failure' for nil:NilClass)

````

https://github.com/yanana/fluent-plugin-filter-list/blob/4e6e9cbda70fb4a7075f72a2611e0206792441cc/lib/matcher.rb#L23

At the first transition to `e`, it `node` will be nil.
